#!/usr/bin/env bash

################################################################################
# Mac OS X stuff
# author: JP Camargo
################################################################################

# configurations
export EDITOR="mvim -f --nomru -c \"au VimLeave * !open -a iTerm2\""

export SUBL_EDITOR="subl -w"

export VIM_EDITOR="mvim -f --nomru -c \"au VimLeave * !open -a iTerm2\""

export GREP_OPTIONS="--color=auto"
export GREP_COLOR="1;33;40"

export CLICOLOR=1
# export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

export HOMEBREW_GITHUB_API_TOKEN=17fe46fc9c7be164148ef698cd0bddbaca6aabc3

# android sdk
export ANDROID_HOME=/usr/local/opt/android-sdk

BREW_PREFIX=$(brew --prefix)

# PATH
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:~/bin:/usr/X11/bin
export PATH=$PATH:${DOTFILES_PATH}/scripts            # dotfiles scripts
export PATH=$PATH:${ANDROID_HOME}/tools               # android sdk
export PATH=$PATH:${GOROOT}/libexec/bin:${GOPATH}/bin # go lang
export PATH=$PATH:/usr/local/heroku/bin               # heroku
export PATH=$PATH:$HOME/.rvm/bin                      # rvm

[ -d $BREW_PREFIX ] && export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH

export PATH=`echo $PATH | tr ':' '\n' | uniq | tr '\n' ':'`

# Homebrew
# source $BREW_PREFIX/Library/Contributions/brew_bash_completion.sh

# go root
if [ -d $BREW_PREFIX ]; then
  export GOROOT=$BREW_PREFIX/Cellar/go/1.2.2/libexec
fi
export GOPATH=$HOME/go

# load bash completion from brew
[ -f $BREW_PREFIX/etc/bash_completion ] && source $BREW_PREFIX/etc/bash_completion

# load git awesomeness
[ -f $BREW_PREFIX/etc/bash_completion.d/git-completion.bash ] && source $BREW_PREFIX/etc/bash_completion.d/git-completion.bash
[ -f $BREW_PREFIX/etc/bash_completion.d/git-prompt.sh ] && source $BREW_PREFIX/etc/bash_completion.d/git-prompt.sh

# load android adb
[ -f $BREW_PREFIX/etc/bash_completion.d/adb-completion.bash ] && source $BREW_PREFIX/etc/bash_completion.d/adb-completion.bash

# go lang completion
[ -f $BREW_PREFIX/etc/bash_completion.d/go-completion.bash ] && source $BREW_PREFIX/etc/bash_completion.d/go-completion.bash

# load ack completion
[ -f $DOTFILES_PATH/ack_completion ] && [[ " $(brew list) " =~ " ack " ]] && source $DOTFILES_PATH/ack_completion

# pow completion
[ -f $BREW_PREFIX/etc/pow_completion ] && complete -C $DOTFILES_PATH/pow_completion -o default pow

################################################################################
# Aliases
################################################################################

# editor related shortcuts
alias ls="ls --color"

alias v="mvim"

alias vim="vim -u ~/.vim/vimrc"
alias mvim="mvim -u ~/.vim/vimrc"

# lock and screen
alias lock='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
alias screensaver='open -a /System/Library/Frameworks/ScreenSaver.framework//Versions/A/Resources/ScreenSaverEngine.app'

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume 10'"
alias hax="growlnotify -a 'Activity Monitor' 'System error' -m 'WTF R U DOIN'"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

################################################################################
# Functions
################################################################################

# reload source
reload () { source ~/.bash_profile; }

# open man page in Preview
man2pdf () { man -t $* | open -f -a Preview; }

# mac downloads log
show_downloads() {
  sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'select LSQuarantineDataURLString from LSQuarantineEvent'
}

clear_downloads() {
  sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'
}

# pow
pow () {
  case $1 in
    about)
      open "http://pow.cx";;
    app)
      local pow_app=`pwd`;
      case $2 in
        delete)
          if [ -z "$3" ]; then
            rm -i ~/.pow/$3
          else
            rm -i ~/.pow/$pow_app
          fi;;
        list)
          ls -la ~/.pow/;;
        new)
          ln -sf $pow_app ~/.pow/${pow_app##*/}
          ls -lA ~/.pow/ | grep ${pow_app##*/}
        ;;
        restart)
          echo "restarting app..."
          touch tmp/restart.txt;;
        *)
          echo "App info"
          echo $pow_app;;
      esac;;
    powrc)
      case $2 in
        show)
          if [ -f .powrc ]; then
            _style_colorize ".powrc contents" 33
            cat .powrc
          else
            _style_colorize ".powrc not found" 31
          fi
          ;;
        write)
          cp $DOTFILES_PATH/powrc_base .powrc
          _style_colorize ".powrc contents" 32
          cat .powrc
          ;;
      esac
      ;;
    endpoint)
      curl -H host:pow localhost/status.json
      echo;;
    manual)
      open "http://pow.cx/manual.html";;
    portproxy)
      echo $2 > ~/.pow/$3;;
    restart)
      echo "restarting Pow..."
      touch ~/.pow/restart.txt;;
    rvm)
      if [ ! -f .ruby-version ] || [ ! -f .ruby-gemset ]; then
        _style_colorize "Creating rvm files" 33
        rvm use $(cat .rvmrc.example | grep @ | awk -F' ' '{ print $2 }') --ruby-version --create
      else
        _style_colorize ".ruby-version contents" 33
        cat .ruby-version
        _style_colorize ".ruby-gemset contents" 33
        cat .ruby-gemset
      fi
      ;;
    uninstall)
      curl get.pow.cx/uninstall.sh | sh;;
    upgrade)
      curl get.pow.cx | sh;;
    help|*)
      echo "Pow Rack Server:
      about
      endpoint
      help
      manual
      portproxy
        pow portproxy port# appname
      powrc
        show write
      restart
      upgrade
      uninstall";;
  esac
}

# iso to img using hdiutil
iso2img () {
  if [ "$1" != "" ] && [ "$2" != "" ]; then
    hdiutil convert -format UDRW -o $2 $1;
  else
    echo "Missing arguments, usage:
  iso2img <image_file> <output_file>"
  fi
}

_battery_status () {
  local response=$(pmset -g batt)
}

_archey () {
  archey --color
}
_archey
