#!/usr/bin/env bash

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want

# locaweb deploy tools
ldt () {
  [ ! -d .git ] && _style_error "Not a repo, can't continue." && return
  local dir=`pwd`
  local repo=${dir##*/}
  local system="${repo##*-}"
  local machine=''; local area=''

  if [ -f .locatools ]; then
    source .locatools
  fi

  [ "$area" == "" ] && area='registro'
  [ "$machine" == "" ] && machine='services'

  if [ "$machine" != "" ] && [ "${machine##*-}" != "sys1" ] && [ "$system" == "sys1" ]; then
    machine="${machine}-sys1"
  fi

  local url="http://deploy.${machine}.${area}.systemintegration.locaweb.com.br"

  case $1 in
    delete)
      url="${url}/pkg/${repo}"
      _style_title "Removing $repo"
      echo -e " curl -XDELETE -i -d '' $url\n"
      curl -XDELETE -i -d '' ${url}
      echo ""
      ;;
    deploy)
      ldt stop
      ldt update
      ldt start
      echo ""
      ;;
    install)
      url="${url}/pkg/${repo}"
      _style_title "Installing $repo"
      echo -e " curl -XPOST -i -d '' $url\n"
      curl -XPOST -i -d '' ${url}
      echo ""
      ;;
    update)
      url="${url}/pkg/${repo}"
      _style_title "Updating $repo"
      echo -e " curl -XPUT -i -d '' $url\n"
      curl -XPUT -i -d '' ${url}
      echo ""
      ;;
    pkginfo)
      url="${url}/pkg/${repo}"
      _style_title "Getting info for $repo"
      echo -e " curl -i $url\n"
      curl -i ${url}
      echo ""
      ;;
    status)
      url="${url}/daemon/${repo}/status"
      _style_title "Getting status for $repo"
      echo -e " curl -i $url\n"
      curl -i ${url}
      echo ""
      ;;
    restart)
      url="${url}/daemon/${repo}/restart"
      _style_title "Restarting $repo"
      echo -e " curl -i $url\n"
      curl -i ${url}
      echo ""
      ;;
    stop)
      url="${url}/daemon/${repo}/stop"
      _style_title "Stopping $repo"
      echo -e " curl -i $url\n"
      curl -i ${url}
      echo ""
      ;;
    start)
      url="${url}/daemon/${repo}/start"
      _style_title "Starting $repo"
      echo -e " curl -i $url\n"
      curl -i ${url}
      echo ""
      ;;
    logs)
      url="${url}/logs/syslog"
      _style_title "Showing logs for $repo"
      echo -e " curl -i $url\n"
      curl -i "${url}?type=tail&lines=200"
      echo ""
      ;;
    *)
      echo -e "Usage:\n  ldt (deploy|start|stop|...)"
      ;;
  esac
}

