#!/usr/bin/env bash

DOTFILES=`pwd`
TMPDIR=`echo $DOTFILES | sed "s|$HOME/||"`

cd $HOME

# Files to link
# .bash_completion.sh
# .bash_profile
# .bash_functions
# .gemrc
# .git_completion.sh
# .gitconfig
# .gitignore
# .aprc
# .rvmrc

for FILE in ".bash_profile" ".bash_functions" ".bash_completion.sh" ".gemrc" ".git_completion.sh" ".gitconfig" ".gitignore" ".aprc" ".rvmrc"
do
  # removing existing file, if exists
  if [ -f $FILE ]; then
    rm $FILE
  fi
  
  # linking project file, if exists
  if [ -f $TMPDIR/$FILE ]; then
    ln -s $TMPDIR/$FILE $FILE
  fi
  ls -laG $FILE
done

# reading the profile
source .bash_profile

# listing symbolic links
ls -laG | grep '\>'

cd $DOTFILES
