#!/usr/bin/env bash

DOTFILES=`pwd`
DOTFILES_DIR=`echo $DOTFILES | sed "s|$HOME/||"`

# Files to link
# .bash_profile
# .bash_functions
# .gemrc
# .gitconfig
# .gitignore_global
# .aprc
# .rvmrc
# .ackrc

cd $HOME

for FILE in "bash_profile" "bash_functions" "gemrc" "gitconfig" "gitignore_global" "aprc" "rvmrc" "ackrc"
do
  # removing existing file, if exists
  if [ -f .$FILE ]; then
    rm .$FILE
  fi
  
  # linking project file, if exists
  if [ -f $DOTFILES_DIR/$FILE ]; then
    ln -s $DOTFILES_DIR/$FILE .$FILE
  fi
  ls -laG .$FILE
done

# reading the profile
source .bash_profile
