set nocompatible " turn off Vi compatibility mode
filetype off " required (to be honest, I don't know why :P)

" Vundle
" ======
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
filetype plugin indent on
Bundle 'gmarik/vundle' " required!

" CSApprox
" Bundle 'CSApprox'

" CtrlP
Bundle 'kien/ctrlp.vim'

" SuperTab continued
Bundle 'ervandew/supertab'

" Gist.vim
Bundle 'mattn/webapi-vim'
Bundle 'mattn/gist-vim'
let g:gist_detect_filetype = 1 " autodetect gist filetype
let g:gist_open_browser_after_post = 1 " open browser after create a gist
let g:gist_post_private = 1 " create private gist by default

" fugitive.vim
Bundle 'tpope/vim-fugitive'

" Powerline
Bundle 'Lokaltog/vim-powerline'
let g:Powerline_symbols = 'unicode'
let g:Powerline_colorscheme = 'skwp'

" Snipmate
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "honza/vim-snippets"
Bundle "garbas/vim-snipmate"

" Command-T
Bundle "git://git.wincent.com/command-t.git"
let g:CommandTMatchWindowAtTop=1 " show window at top

" VIM setup
" =========

set mouse=a                 " Automatically enable mouse usage
set mousehide               " Hide the mouse cursor while typing

set laststatus=2 " always show the status line

set guifont=Monaco:h12
set wrap " quebra de linhas

set lines=999
set columns=999

set encoding=utf-8

set number " show line numbers
set showmode " show current mode on status line
set showcmd " show commands on status line
set nowrap " disable automatic word wrapping

set history=300 " number of commands saved in the history list
set undolevels=300 " number of undo levels

set backupdir=~/.vim/tmp " the directory where the swap/backup files should be stored
set dir=~/.vim/tmp

set backup " turn on backup
set swapfile

set title " show the current filename on the window title
set backspace=eol,start,indent " allow backspacing over everything in insert mode

set ruler " show the cursor position on status line

set hidden " allow Vim to manage multiple buffers effectively

set tabstop=2 " default tab size
set shiftwidth=2
set expandtab " convert tabs to spaces
set autoindent " self explanatory, huh? (like the most of commands hehe)

set list
"set listchars=tab:▷⋅,trail:⋅,nbsp:⋅ " show tabs and trailing spaces

set t_Co=256 " the term has 256 colors

set hlsearch " highlight search
set incsearch " show matches while typing

syntax on " turn on syntax highlighting
colorscheme twilight " the color scheme (srsly)
"set background=light
"let g:solarized_termcolors=256
"colorscheme solarized

"Trailing Space Remove
autocmd BufWritePre * :%s/\s\+$//e

" ****************************************************************
" LANGUAGUE INDENT CONFIGURATION
" ****************************************************************
autocmd FileType make       set noexpandtab

autocmd FileType eruby      call UseTabs()
autocmd FileType html       call UseTabs()
autocmd FileType xhtml      call UseTabs()
autocmd FileType sh         call UseTabs()
autocmd FileType xml        call UseTabs()

autocmd FileType ruby       set expandtab sw=2 ts=2 sts=2
autocmd FileType python     set expandtab sw=4 ts=4 sts=4
autocmd FileType javascript set expandtab sw=4 ts=4 sts=4
autocmd FileType tex        call Writing()
autocmd FileType plaintex   call Writing()
autocmd FileType vimwiki    call Writing()
autocmd FileType markdown   call Writing()

set wildmode=list:longest                       " Make cmdline tab completion similar to bash
set listchars=tab:\ \ ,extends:>,precedes:<     " Special chars to show tabs, eol and bol

