#!/bin/sh

if [ -d /Volumes/Lacie/Pictures -a -w /Volumes/Lacie/Pictures ]; then
  echo -e "\033[0;33mBackup from hdd to Lacie disk\033[0m";
  rsync --archive --update --recursive --progress --human-readable --prune-empty-dirs --info=progress2 ~/Pictures/ /Volumes/LaCie/Pictures/ --exclude '.DS_Store';
fi

if [ -d /Volumes/Backup/Pictures -a -w /Volumes/Backup/Pictures ]; then
  echo "\033[0;33mBackup from hdd to Seagate disk\033[0m";
  rsync --archive --update --recursive --progress --human-readable --prune-empty-dirs --info=progress2 ~/Pictures/ /Volumes/Backup/Pictures/ --exclude '.DS_Store';
fi

if [[ -d /Volumes/Lacie/Pictures && -d /Volumes/Backup/Pictures ]]; then
  echo -e "\033[0;33m\]Backup from Lacie disk to Seagate disk\033[0m";
  rsync --archive --update --recursive --progress --human-readable --prune-empty-dirs --info=progress2 /Volumes/Lacie/Pictures/ /Volumes/Backup/Pictures/ --exclude '.DS_Store';
fi
