#!/usr/bin/env ruby

require "rubygems"
require "rspec"

a, b, c, d, e = 4, 6, 6, 3, 7

describe "Dropbox" do
  context "Dropbox password test" do
    it "product of a and b should equals 24" do
      (a * b).should == 24
    end

    it "b should have double of d's value" do
      b.should == 2*d
    end
    
    it "a plub c should equal d plus e" do
      (a + c).should  == (d + e)
    end
    
    it "sum of all 5 items should be 26" do
      (a + b + c + d + e).should == 26
    end
  end
end
