#!/usr/bin/env bash

# requires: style_functions

. $DOTFILES_PATH/style_functions

BASEDIR=$(basename `pwd`)

_pull_fetch () {
  local DIR=`pwd`

  remote=$(git remote)
  printf "\r\e[K$(_style_colorize "${DIR#*$BASEDIR/}" 32) => Fetching $remote"
  git fetch --all 2>&1 | tr '\n' ' '

  branch=$(git branch 2>&1 | grep \* | sed 's/* //')
  printf "\r\e[K$(_style_colorize "${DIR#*$BASEDIR/}" 32) => Pulling $remote/$branch, "
  git pull --rebase 2>&1 | tr '\n' ' ' | sed "s/Current branch ${branch}/branch/g"
}

_list_directories () {
for dir in `ls`; do
  if [ -d $dir ]; then
    if [ -d $dir/.git ] && [ ! -f .pull_all_ignore ]; then
      cd $dir
      _pull_fetch $dir
      cd ..
    else
      if [ ! -f .pull_all_ignore ]; then
        cd $dir
        _list_directories
        cd ..
      fi
    fi
  fi
done
}

_list_directories
