#!/usr/bin/env bash

# requires: style_functions

. $DOTFILES_PATH/style_functions

_pull_fetch () {
  local dir=`pwd`
  _style_title "Updating ${dir#\/Users\/jao\/projects}"
  git fetch --all 2>/dev/null
  git pull --rebase 2>/dev/null
  echo;
}

_list_directories () {
for dir in `ls`; do
  if [ -d $dir ]; then
    if [ -d $dir/.git ]; then
      cd $dir
      _pull_fetch $dir
      cd ..
    else
      cd $dir
      _list_directories
      cd ..
    fi
  fi
done
}

_list_directories
