#!/usr/bin/env ruby
require "fileutils";
Dir.glob("*.*").sort.each_with_index do |file,n|
  # title = file.gsub(/^\d+\s.\s|\.\w{3}/,'')
  FileUtils.mv(file, "Serial.Experiments.Lain.S01E#{"%02d" % (n + 1)}.720p.mkv")
end
