#!/usr/bin/env bash
# defaults write com.apple.finder AppleShowAllFiles FALSE

STATUS=`defaults read com.apple.finder AppleShowAllFiles`
if [ "$STATUS" = "FALSE" ]; then
  defaults write com.apple.finder AppleShowAllFiles FALSE
else
  defaults write com.apple.finder AppleShowAllFiles TRUE
fi