#!/bin/bash
# 
# wms_content_to_ams:
# this script is meant to copy the main files from the italian content format
# to a new structure that will be used to create the AMS XML files to import
# the contents into the german platorm.
# 
# There will be another script to generate the XML files, filling all the
# available information.
# 

# Basic variables
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`dirname $0`
source "${SCRIPT_DIR}/_function_colorize"

CONTENT_SOURCE_DIRECTORY="/Volumes/PublicoSP/remoteITcontents/remote"
CONTENT_TARGET_DIRECTORY="/Volumes/PublicoSP/remoteITcontents/ams"

# script starts here

# go to the content's source directory
cd "${CONTENT_SOURCE_DIRECTORY}"
for content_dir in `ls`; do
  if [ -d "${content_dir}" ]; then
    case $content_dir in
      games)
        # copy the TXT files, IMG files, and JAVA files to a simpler file structure
        banner "Copying game files" 37 44
        cd "${content_dir}"
        
        for dir in `ls`; do
          if [ -d "${dir}" ]; then
            colorize "  working with files in ${dir}" 36
            
            provider="${dir##*_}"
            provider_name=`echo "$provider" | tr "[:upper:]" "[:lower:]"`
            game="${dir%_*}"
            game="${game%jogo*}"
            game="${game%Jogo*}"
            game_name=`echo "$game" | tr "[:upper:]" "[:lower:]"`
            
            target_dir="${CONTENT_TARGET_DIRECTORY}/games/${provider_name}/${game_name}"
            [ ! -d "${target_dir}" ] && mkdir -p "${target_dir}"
            
            cd "${dir}"
            files_in_target_dir=`ls | wc -w | sed 's/ //'`
            if [ "${files_in_target_dir}" -eq 0 ]; then
              colorize "    copying game files to ${target_dir}/"
              cp IMG/*.GIF "${target_dir}/"
              cp TXT/*.TXT "${target_dir}/"
              cp FILES/*/*.JA* "${target_dir}/"
            else
              colorize "    there are files in ${target_dir} already, please fix this" 35
            fi
            cd ..
            
          fi
        done
        
        cd ..
        colorize "Game files copied." 32
      ;;
      images)
        # copy only the larger resolution image files to a simpler file structure
        banner "Copying image files" 37 44
        cd "${content_dir}"
        
        for dir in `ls`; do
          if [ -d "${dir}" ]; then
            colorize "  working with files inside ${dir}" 36
            
            provider="${dir##*_}"
            provider_name=`echo "$provider" | tr "[:upper:]" "[:lower:]"`
            
            target_dir="${CONTENT_TARGET_DIRECTORY}/images/${provider_name}"
            [ ! -d "${target_dir}" ] && mkdir -p "${target_dir}"
            
            # find the name patterns inside this directory
            
            # find the larger resolution image available that follows that name pattern
            
            # copy it to the target directory
            
          fi
        done
        
        cd ..
        colorize "Image files copied." 32
      ;;
      songs)
        # copy the sound files to a simpler file structure
        banner "Copying song files" 37 44
        cd "${content_dir}"
        
        for dir in `ls`; do
          if [ -d "${dir}" ]; then
            colorize "  working with files inside ${dir}" 36
            
            provider="${dir##*_}"
            provider_name=`echo "$provider" | tr "[:upper:]" "[:lower:]"`
            
            cd "${dir}"
            for song_dir in `ls`
              song_name="${song_dir}"
              target_dir="${CONTENT_TARGET_DIRECTORY}/songs/${provider_name}/${song_name}"
              [ ! -d "${target_dir}" ] && mkdir -p "${target_dir}"
              
              cd "${song_dir}"
              files_in_target_dir=`ls | wc -w | sed 's/ //'`
              if [ "${files_in_target_dir}" -eq 0 ]; then
                colorize "    copying song files to ${target_dir}/"
                cp * "${target_dir}/"
                cp REAL/* "${target_dir}/"
              else
                colorize "    there are files in ${target_dir} already, please fix this" 35
              fi
              cd ..
            done
            cd ..
            
          fi
        done
        
        cd ..
        colorize "Song files copied." 32
      ;;
      videos)
        # copy the larger resolution video files to a simpler file structure
        banner "Copying video files" 37 44
        cd "${content_dir}"
        
        for dir in `ls`; do
          if [ -d "${dir}" ]; then
            colorize "  working with files inside ${dir}" 36
            
            provider="${dir##*_}"
            provider_name=`echo "$provider" | tr "[:upper:]" "[:lower:]"`
            
            target_dir="${CONTENT_TARGET_DIRECTORY}/videos/${provider_name}"
            [ ! -d "${target_dir}" ] && mkdir -p "${target_dir}"
            
            # find the name patterns inside this directory
            
            # find the larger resolution video available that follows that name pattern
            
            # copy it to the target directory
            
          fi
        done
        
        cd ..
        colorize "Video files copied." 32
      ;;
    esac
  fi
done

exit $?
